# Generated by Django 4.2.2 on 2023-06-23 14:33

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=50, samples=None, unique=True)),
            ],
        ),
    ]
